import { StyleSheet } from 'react-native';
import fonts from '../../styles/fonts';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f8f9fa',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 16,
        paddingTop: 50,
        paddingBottom: 12,
        backgroundColor: '#fff',
        borderBottomWidth: 1,
        borderBottomColor: '#e8eaed',
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#202124',
        fontFamily: fonts.text,
    },
    content: {
        flex: 1,
        padding: 14,
    },
    card: {
        backgroundColor: '#ffffff',
        borderRadius: 12,
        padding: 16,
        marginBottom: 12,
        shadowColor: 'rgba(0,0,0,0.06)',
        shadowOpacity: 0.06,
        elevation: 2,
        shadowRadius: 6,
        shadowOffset: { width: 0, height: 1 },
    },
    headerCard: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 10,
    },
    categoryBadge: {
        borderRadius: 6,
        paddingHorizontal: 10,
        paddingVertical: 4,
    },
    categoryText: {
        color: '#fff',
        fontSize: 12,
        fontWeight: 'bold',
        fontFamily: fonts.text,
        textTransform: 'uppercase',
    },
    urgencyBadge: {
        backgroundColor: '#fce8e6',
        borderRadius: 6,
        paddingHorizontal: 10,
        paddingVertical: 4,
    },
    urgencyText: {
        color: '#d93025',
        fontSize: 12,
        fontWeight: '600',
        fontFamily: fonts.text,
    },
    title: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#202124',
        fontFamily: fonts.text,
        marginBottom: 6,
    },
    description: {
        fontSize: 15,
        color: '#5f6368',
        fontFamily: fonts.text,
        lineHeight: 22,
        marginBottom: 10,
    },
    locationRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 10,
    },
    locationText: {
        fontSize: 13,
        color: '#5f6368',
        fontFamily: fonts.text,
        marginLeft: 6,
    },
    statsRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        borderTopWidth: 1,
        borderTopColor: '#f1f3f4',
        paddingTop: 10,
    },
    statsText: {
        fontSize: 12,
        color: '#80868b',
        fontFamily: fonts.text,
    },
    actionsRow: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        backgroundColor: '#fff',
        borderRadius: 12,
        paddingVertical: 12,
        marginBottom: 12,
        shadowColor: 'rgba(0,0,0,0.04)',
        shadowOpacity: 0.04,
        elevation: 1,
    },
    actionBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 14,
        paddingVertical: 6,
        borderRadius: 20,
    },
    actionBtnActive: {
        backgroundColor: '#e8f0fe',
    },
    actionBtnText: {
        fontSize: 14,
        color: '#5f6368',
        fontFamily: fonts.text,
        marginLeft: 6,
        fontWeight: '600',
    },
    actionBtnTextActive: {
        color: '#1a73e8',
    },
    commentsSection: {
        backgroundColor: '#fff',
        borderRadius: 12,
        padding: 14,
        marginBottom: 20,
        shadowColor: 'rgba(0,0,0,0.04)',
        shadowOpacity: 0.04,
        elevation: 1,
    },
    commentsTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#202124',
        fontFamily: fonts.text,
        marginBottom: 10,
    },
    inputRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
    },
    commentInput: {
        flex: 1,
        borderWidth: 1,
        borderColor: '#dadce0',
        borderRadius: 20,
        paddingHorizontal: 14,
        paddingVertical: 8,
        fontSize: 14,
        fontFamily: fonts.text,
        color: '#202124',
        maxHeight: 80,
    },
    sendButton: {
        backgroundColor: '#1a73e8',
        borderRadius: 20,
        padding: 10,
        marginLeft: 8,
    },
    emptyText: {
        fontSize: 13,
        color: '#80868b',
        fontFamily: fonts.text,
        textAlign: 'center',
        marginVertical: 14,
    },
    commentItem: {
        borderTopWidth: 1,
        borderTopColor: '#f1f3f4',
        paddingVertical: 10,
    },
    commentHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 4,
    },
    commentAuthor: {
        fontSize: 13,
        fontWeight: 'bold',
        color: '#202124',
        fontFamily: fonts.text,
    },
    commentDate: {
        fontSize: 11,
        color: '#80868b',
        fontFamily: fonts.text,
    },
    commentText: {
        fontSize: 14,
        color: '#5f6368',
        fontFamily: fonts.text,
        lineHeight: 20,
    },
});

